# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layawayapp', '0002_artist_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('VIP', 'VIP'), ('GEN', 'GENERAL')], max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('confirmation_number', models.CharField(max_length=20)),
                ('ticket_number', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('VIP', 'VIP'), ('GEN', 'GENERAL')], max_length=12)),
                ('maxTickets', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='layawayapp.Artist'),
        ),
        migrations.AddField(
            model_name='ticketinfo',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_info_events', to='layawayapp.Events'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_events', to='layawayapp.Events'),
        ),
    ]
